const PRODUCTS = [
  {
    id: 1,
    name: "Biquíni Azul-Marinho",
    category: "Biquínis",
    price: 79.90,
    color: "Azul",
    sizes: ["P", "M", "G"],
    occasion: "Praia",
    image: "imagens/Biquíni Azul-Marinho.jpg",
    images: ["imagens/Biquíni Azul-Marinho.jpg", "imagens/Biquíni Azul-Marinho - visualizacao 2.jpg", "imagens/Biquíni Azul-Marinho - visualizacao 3.jpg", "imagens/Biquíni Azul-Marinho - visualizacao 4.jpg"],
    desc: "Biquíni feminino azul-marinho com visual moderno e confortável para dias de praia e piscina.",
    composition: "82% poliamida e 18% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril"], "rows": [["P", "82–86 cm", "64–68 cm", "88–92 cm"], ["M", "86–90 cm", "68–72 cm", "92–96 cm"], ["G", "90–94 cm", "72–76 cm", "96–100 cm"]]},
    tags: "biquini azul marinho praia piscina verão",
    promo: true,
    bestseller: true
  },

  {
    id: 2,
    name: "Blusa Cropped Vinho",
    category: "Blusas",
    price: 64.90,
    color: "Vinho",
    sizes: ["PP", "P", "M", "G"],
    occasion: "Festa",
    image: "imagens/Blusa Cropped Vinho.jpg",
    images: ["imagens/Blusa Cropped Vinho.jpg", "imagens/Blusa Cropped Vinho - visualizacao 2.jpg", "imagens/Blusa Cropped Vinho - visualizacao 3.jpg", "imagens/Blusa Cropped Vinho - visualizacao 4.jpg"],
    desc: "Blusa cropped em tom vinho, com modelagem moderna para produções marcantes.",
    composition: "90% poliamida e 10% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Comprimento"], "rows": [["PP", "78–82 cm", "58–62 cm", "39 cm"], ["P", "82–86 cm", "62–66 cm", "40 cm"], ["M", "86–90 cm", "66–70 cm", "41 cm"], ["G", "90–96 cm", "70–76 cm", "42 cm"]]},
    tags: "blusa cropped vinho festa balada",
    promo: true,
    bestseller: true
  },

  {
    id: 3,
    name: "Bracelete Espiral de Braço",
    category: "Acessórios",
    price: 34.90,
    color: "Prata",
    sizes: ["Único"],
    occasion: "Festa",
    image: "imagens/Bracelete Espiral de Braço.jpg",
    images: ["imagens/Bracelete Espiral de Braço.jpg", "imagens/Bracelete Espiral de Braço - visualizacao 2.jpg", "imagens/Bracelete Espiral de Braço - visualizacao 3.jpg", "imagens/Bracelete Espiral de Braço - visualizacao 4.jpg"],
    desc: "Bracelete espiral de braço para complementar looks com personalidade.",
    composition: "Liga metálica e materiais sintéticos.",
    measurements: {"headers": ["Tamanho", "Circunferência", "Altura"], "rows": [["Único", "20–24 cm", "8 cm"]]},
    tags: "bracelete espiral acessorio prata festa",
    promo: true,
    bestseller: false
  },

  {
    id: 4,
    name: "Calça de Moletom Flare Cinza",
    category: "Calças",
    price: 99.90,
    color: "Cinza",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Calça de Moletom Flare Cinza.jpg",
    images: ["imagens/Calça de Moletom Flare Cinza.jpg", "imagens/Calça de Moletom Flare Cinza - visualizacao 2.jpg", "imagens/Calça de Moletom Flare Cinza - visualizacao 3.jpg", "imagens/Calça de Moletom Flare Cinza - visualizacao 4.jpg"],
    desc: "Calça de moletom flare cinza, confortável e perfeita para produções casuais.",
    composition: "88% algodão e 12% poliéster.",
    measurements: {"headers": ["Tamanho", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "64–68 cm", "90–94 cm", "104 cm"], ["M", "68–72 cm", "94–98 cm", "105 cm"], ["G", "72–78 cm", "98–104 cm", "106 cm"], ["GG", "78–84 cm", "104–110 cm", "107 cm"]]},
    tags: "calca moletom flare cinza casual confortável",
    promo: true,
    bestseller: true
  },

  {
    id: 5,
    name: "Calça Jeans Flare Bordada",
    category: "Calças",
    price: 109.90,
    color: "Azul",
    sizes: ["PP", "P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Calça Jeans Flare Bordada.jpg",
    images: ["imagens/Calça Jeans Flare Bordada.jpg", "imagens/Calça Jeans Flare Bordada - visualizacao 2.jpg", "imagens/Calça Jeans Flare Bordada - visualizacao 3.jpg", "imagens/Calça Jeans Flare Bordada - visualizacao 4.jpg"],
    desc: "Calça jeans flare com detalhes bordados e modelagem moderna.",
    composition: "98% algodão e 2% elastano.",
    measurements: {"headers": ["Tamanho", "Cintura", "Quadril", "Comprimento"], "rows": [["PP", "60–64 cm", "86–90 cm", "106 cm"], ["P", "64–68 cm", "90–94 cm", "107 cm"], ["M", "68–72 cm", "94–98 cm", "108 cm"], ["G", "72–78 cm", "98–104 cm", "109 cm"], ["GG", "78–84 cm", "104–110 cm", "110 cm"]]},
    tags: "calca jeans flare bordada azul casual",
    promo: false,
    bestseller: true
  },

  {
    id: 6,
    name: "Camisa com Corset Preto",
    category: "Blusas",
    price: 89.90,
    color: "Preto",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Festa",
    image: "imagens/Camisa com Corset Preto.jpg",
    images: ["imagens/Camisa com Corset Preto.jpg", "imagens/Camisa com Corset Preto - visualizacao 2.jpg", "imagens/Camisa com Corset Preto - visualizacao 3.jpg", "imagens/Camisa com Corset Preto - visualizacao 4.jpg"],
    desc: "Camisa preta com detalhe de corset, ideal para looks modernos e sofisticados.",
    composition: "95% poliéster e 5% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Comprimento"], "rows": [["P", "82–86 cm", "64–68 cm", "58 cm"], ["M", "86–90 cm", "68–72 cm", "59 cm"], ["G", "90–96 cm", "72–78 cm", "60 cm"], ["GG", "96–102 cm", "78–84 cm", "61 cm"]]},
    tags: "camisa corset preta festa balada",
    promo: true,
    bestseller: true
  },

  {
    id: 7,
    name: "Camisa Oversized Rosa",
    category: "Blusas",
    price: 69.90,
    color: "Rosa",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Camisa Oversized Rosa.jpg",
    images: ["imagens/Camisa Oversized Rosa.jpg", "imagens/Camisa Oversized Rosa - visualizacao 2.jpg", "imagens/Camisa Oversized Rosa - visualizacao 3.jpg", "imagens/Camisa Oversized Rosa - visualizacao 4.jpg"],
    desc: "Camisa oversized rosa para composições confortáveis e estilosas.",
    composition: "100% algodão.",
    measurements: {"headers": ["Tamanho", "Busto", "Comprimento", "Manga"], "rows": [["P", "88–94 cm", "68 cm", "21 cm"], ["M", "94–100 cm", "70 cm", "22 cm"], ["G", "100–106 cm", "72 cm", "23 cm"], ["GG", "106–112 cm", "74 cm", "24 cm"]]},
    tags: "camisa oversized rosa casual streetwear",
    promo: true,
    bestseller: false
  },

  {
    id: 8,
    name: "Casaco Moletom Oversized com Estrela",
    category: "Casacos",
    price: 129.90,
    color: "Preto",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Casaco Moletom Oversized com Estrela.jpg",
    images: ["imagens/Casaco Moletom Oversized com Estrela.jpg", "imagens/Casaco Moletom Oversized com Estrela - visualizacao 2.jpg", "imagens/Casaco Moletom Oversized com Estrela - visualizacao 3.jpg", "imagens/Casaco Moletom Oversized com Estrela - visualizacao 4.jpg"],
    desc: "Casaco de moletom oversized com detalhe de estrela, aconchegante e urbano.",
    composition: "80% algodão e 20% poliéster.",
    measurements: {"headers": ["Tamanho", "Busto", "Comprimento", "Manga"], "rows": [["P", "96–102 cm", "68 cm", "58 cm"], ["M", "102–108 cm", "70 cm", "59 cm"], ["G", "108–114 cm", "72 cm", "60 cm"], ["GG", "114–120 cm", "74 cm", "61 cm"]]},
    tags: "casaco moletom oversized estrela preto casual",
    promo: false,
    bestseller: false
  },

  {
    id: 9,
    name: "Colar Gótico com Cruz",
    category: "Acessórios",
    price: 39.90,
    color: "Prata",
    sizes: ["Único"],
    occasion: "Festa",
    image: "imagens/Colar Gótico com Cruz.jpg",
    images: ["imagens/Colar Gótico com Cruz.jpg", "imagens/Colar Gótico com Cruz - visualizacao 2.jpg", "imagens/Colar Gótico com Cruz - visualizacao 3.jpg", "imagens/Colar Gótico com Cruz - visualizacao 4.jpg"],
    desc: "Colar com cruz e estética gótica para completar produções cheias de personalidade.",
    composition: "Aço inoxidável e corrente metálica.",
    measurements: {"headers": ["Tamanho", "Comprimento", "Largura do pingente"], "rows": [["Único", "45 cm", "3 cm"]]},
    tags: "colar gotico cruz prata acessorio festa",
    promo: true,
    bestseller: false
  },

  {
    id: 10,
    name: "Conjunto de Renda Marrom",
    category: "Conjuntos",
    price: 119.90,
    color: "Marrom",
    sizes: ["P", "M", "G"],
    occasion: "Romântico",
    image: "imagens/Conjunto de Renda Marrom.jpg",
    images: ["imagens/Conjunto de Renda Marrom.jpg", "imagens/Conjunto de Renda Marrom - visualizacao 2.jpg", "imagens/Conjunto de Renda Marrom - visualizacao 3.jpg", "imagens/Conjunto de Renda Marrom - visualizacao 4.jpg"],
    desc: "Conjunto de renda marrom com visual delicado e sofisticado.",
    composition: "90% poliamida e 10% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "82–86 cm", "64–68 cm", "88–92 cm", "56 cm"], ["M", "86–90 cm", "68–72 cm", "92–96 cm", "57 cm"], ["G", "90–96 cm", "72–78 cm", "96–102 cm", "58 cm"]]},
    tags: "conjunto renda marrom romantico delicado",
    promo: false,
    bestseller: true
  },

  {
    id: 11,
    name: "Conjunto Esportivo Rosa",
    category: "Conjuntos",
    price: 99.90,
    color: "Rosa",
    sizes: ["P", "M", "G"],
    occasion: "Esportivo",
    image: "imagens/Conjunto Esportivo Rosa.jpg",
    images: ["imagens/Conjunto Esportivo Rosa.jpg", "imagens/Conjunto Esportivo Rosa - visualizacao 2.jpg", "imagens/Conjunto Esportivo Rosa - visualizacao 3.jpg", "imagens/Conjunto Esportivo Rosa - visualizacao 4.jpg"],
    desc: "Conjunto esportivo rosa para acompanhar momentos de movimento com conforto.",
    composition: "88% poliamida e 12% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "80–84 cm", "60–64 cm", "86–90 cm", "55 cm"], ["M", "84–88 cm", "64–68 cm", "90–94 cm", "56 cm"], ["G", "88–94 cm", "68–74 cm", "94–100 cm", "57 cm"]]},
    tags: "conjunto esportivo rosa academia fitness",
    promo: true,
    bestseller: false
  },

  {
    id: 12,
    name: "Conjunto Fitness Cinza",
    category: "Conjuntos",
    price: 89.90,
    color: "Cinza",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Esportivo",
    image: "imagens/Conjunto Fitness Cinza.jpg",
    images: ["imagens/Conjunto Fitness Cinza.jpg", "imagens/Conjunto Fitness Cinza - visualizacao 2.jpg", "imagens/Conjunto Fitness Cinza - visualizacao 3.jpg", "imagens/Conjunto Fitness Cinza - visualizacao 4.jpg"],
    desc: "Conjunto fitness cinza com visual clean e confortável para atividades físicas.",
    composition: "90% poliamida e 10% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "80–84 cm", "60–64 cm", "86–90 cm", "54 cm"], ["M", "84–88 cm", "64–68 cm", "90–94 cm", "55 cm"], ["G", "88–94 cm", "68–74 cm", "94–100 cm", "56 cm"], ["GG", "94–100 cm", "74–80 cm", "100–106 cm", "57 cm"]]},
    tags: "conjunto fitness cinza academia esportivo",
    promo: true,
    bestseller: false
  },

  {
    id: 13,
    name: "Conjunto Infantil Xadrez",
    category: "Infantis",
    price: 84.90,
    color: "Bege",
    sizes: ["PP", "P", "M", "G"],
    occasion: "Casual",
    image: "imagens/Conjunto Infantil Xadrez.jpg",
    images: ["imagens/Conjunto Infantil Xadrez.jpg", "imagens/Conjunto Infantil Xadrez - visualizacao 2.jpg", "imagens/Conjunto Infantil Xadrez - visualizacao 3.jpg", "imagens/Conjunto Infantil Xadrez - visualizacao 4.jpg"],
    desc: "Conjunto infantil xadrez com visual divertido e confortável.",
    composition: "70% algodão e 30% poliéster.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["PP", "58–62 cm", "54–56 cm", "60–64 cm", "45 cm"], ["P", "62–66 cm", "56–58 cm", "64–68 cm", "48 cm"], ["M", "66–70 cm", "58–60 cm", "68–72 cm", "51 cm"], ["G", "70–74 cm", "60–62 cm", "72–76 cm", "54 cm"]]},
    tags: "conjunto infantil xadrez bege criança",
    promo: true,
    bestseller: false
  },

  {
    id: 14,
    name: "Gorro de Tricô com Orelhas de Gato",
    category: "Acessórios",
    price: 49.90,
    color: "Preto",
    sizes: ["Único"],
    occasion: "Casual",
    image: "imagens/Gorro de Tricô com Orelhas de Gato.jpg",
    images: ["imagens/Gorro de Tricô com Orelhas de Gato.jpg", "imagens/Gorro de Tricô com Orelhas de Gato - visualizacao 2.jpg", "imagens/Gorro de Tricô com Orelhas de Gato - visualizacao 3.jpg", "imagens/Gorro de Tricô com Orelhas de Gato - visualizacao 4.jpg"],
    desc: "Gorro de tricô com orelhinhas de gato para deixar a produção mais divertida.",
    composition: "100% acrílico.",
    measurements: {"headers": ["Tamanho", "Circunferência da cabeça", "Altura"], "rows": [["Único", "54–58 cm", "20 cm"]]},
    tags: "gorro trico orelhas gato preto acessorio inverno",
    promo: true,
    bestseller: false
  },

  {
    id: 15,
    name: "Jaqueta Roxo Y2K",
    category: "Casacos",
    price: 119.90,
    color: "Roxo",
    sizes: ["P", "M", "G"],
    occasion: "Casual",
    image: "imagens/Jaqueta Roxo Y2K.jpg",
    images: ["imagens/Jaqueta Roxo Y2K.jpg", "imagens/Jaqueta Roxo Y2K - visualizacao 2.jpg", "imagens/Jaqueta Roxo Y2K - visualizacao 3.jpg", "imagens/Jaqueta Roxo Y2K - visualizacao 4.jpg"],
    desc: "Jaqueta roxa inspirada na estética Y2K, perfeita para looks urbanos.",
    composition: "100% poliéster.",
    measurements: {"headers": ["Tamanho", "Busto", "Comprimento", "Manga"], "rows": [["P", "88–94 cm", "58 cm", "59 cm"], ["M", "94–100 cm", "60 cm", "60 cm"], ["G", "100–106 cm", "62 cm", "61 cm"]]},
    tags: "jaqueta roxa y2k casual urbana",
    promo: false,
    bestseller: false
  },

  {
    id: 16,
    name: "Kimono Branco de Praia",
    category: "Praia",
    price: 89.90,
    color: "Branco",
    sizes: ["P", "M", "G"],
    occasion: "Praia",
    image: "imagens/Kimono Branco de Praia.jpg",
    images: ["imagens/Kimono Branco de Praia.jpg", "imagens/Kimono Branco de Praia - visualizacao 2.jpg", "imagens/Kimono Branco de Praia - visualizacao 3.jpg", "imagens/Kimono Branco de Praia - visualizacao 4.jpg"],
    desc: "Kimono branco leve para complementar biquínis e produções de verão.",
    composition: "100% viscose.",
    measurements: {"headers": ["Tamanho", "Busto", "Comprimento"], "rows": [["P", "84–88 cm", "76 cm"], ["M", "88–94 cm", "78 cm"], ["G", "94–100 cm", "80 cm"]]},
    tags: "kimono branco praia verão saida praia",
    promo: true,
    bestseller: false
  },

  {
    id: 17,
    name: "Luvas de Tricô com Laços",
    category: "Acessórios",
    price: 39.90,
    color: "Preto",
    sizes: ["Único"],
    occasion: "Casual",
    image: "imagens/Luvas de Tricô com Laços.jpg",
    images: ["imagens/Luvas de Tricô com Laços.jpg", "imagens/Luvas de Tricô com Laços - visualizacao 2.jpg", "imagens/Luvas de Tricô com Laços - visualizacao 3.jpg", "imagens/Luvas de Tricô com Laços - visualizacao 4.jpg"],
    desc: "Luvas de tricô com laços delicados para completar produções nos dias frios.",
    composition: "100% acrílico.",
    measurements: {"headers": ["Tamanho", "Comprimento", "Largura da mão"], "rows": [["Único", "20 cm", "9 cm"]]},
    tags: "luvas trico lacos preto acessorio inverno",
    promo: true,
    bestseller: false
  },

  {
    id: 18,
    name: "Saia Jeans com Renda e Amarração",
    category: "Saias",
    price: 74.90,
    color: "Azul",
    sizes: ["PP", "P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Saia Jeans com Renda e Amarração.jpg",
    images: ["imagens/Saia Jeans com Renda e Amarração.jpg", "imagens/Saia Jeans com Renda e Amarração - visualizacao 2.jpg", "imagens/Saia Jeans com Renda e Amarração - visualizacao 3.jpg", "imagens/Saia Jeans com Renda e Amarração - visualizacao 4.jpg"],
    desc: "Saia jeans com renda e amarração, trazendo um toque feminino ao look.",
    composition: "98% algodão e 2% elastano.",
    measurements: {"headers": ["Tamanho", "Cintura", "Quadril", "Comprimento"], "rows": [["PP", "60–64 cm", "86–90 cm", "40 cm"], ["P", "64–68 cm", "90–94 cm", "41 cm"], ["M", "68–72 cm", "94–98 cm", "42 cm"], ["G", "72–78 cm", "98–104 cm", "43 cm"], ["GG", "78–84 cm", "104–110 cm", "44 cm"]]},
    tags: "saia jeans renda amarracao azul casual",
    promo: true,
    bestseller: false
  },

  {
    id: 19,
    name: "Salopete Amarela Infantil",
    category: "Infantis",
    price: 79.90,
    color: "Amarelo",
    sizes: ["PP", "P", "M", "G"],
    occasion: "Casual",
    image: "imagens/Salopete Amarela Infantil.jpg",
    images: ["imagens/Salopete Amarela Infantil.jpg", "imagens/Salopete Amarela Infantil - visualizacao 2.jpg", "imagens/Salopete Amarela Infantil - visualizacao 3.jpg", "imagens/Salopete Amarela Infantil - visualizacao 4.jpg"],
    desc: "Salopete infantil amarela, alegre e confortável para o dia a dia.",
    composition: "100% algodão.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Comprimento"], "rows": [["PP", "58–62 cm", "54–56 cm", "54 cm"], ["P", "62–66 cm", "56–58 cm", "58 cm"], ["M", "66–70 cm", "58–60 cm", "62 cm"], ["G", "70–74 cm", "60–62 cm", "66 cm"]]},
    tags: "salopete amarela infantil criança casual",
    promo: true,
    bestseller: false
  },

  {
    id: 20,
    name: "Sobretudo Preto com Pelúcia",
    category: "Casacos",
    price: 159.90,
    color: "Preto",
    sizes: ["P", "M", "G", "GG"],
    occasion: "Trabalho",
    image: "imagens/Sobretudo Preto com Pelúcia.jpg",
    images: ["imagens/Sobretudo Preto com Pelúcia.jpg", "imagens/Sobretudo Preto com Pelúcia - visualizacao 2.jpg", "imagens/Sobretudo Preto com Pelúcia - visualizacao 3.jpg", "imagens/Sobretudo Preto com Pelúcia - visualizacao 4.jpg"],
    desc: "Sobretudo preto com detalhe de pelúcia para produções elegantes em dias frios.",
    composition: "85% poliéster e 15% viscose.",
    measurements: {"headers": ["Tamanho", "Busto", "Comprimento", "Manga"], "rows": [["P", "88–94 cm", "86 cm", "60 cm"], ["M", "94–100 cm", "88 cm", "61 cm"], ["G", "100–106 cm", "90 cm", "62 cm"], ["GG", "106–112 cm", "92 cm", "63 cm"]]},
    tags: "sobretudo preto pelucia trabalho inverno elegante",
    promo: false,
    bestseller: false
  },

  {
    id: 21,
    name: "Top Regata Floral",
    category: "Blusas",
    price: 59.90,
    color: "Rosa",
    sizes: ["PP", "P", "M", "G"],
    occasion: "Casual",
    image: "imagens/Top Regata Floral.jpg",
    images: ["imagens/Top Regata Floral.jpg", "imagens/Top Regata Floral - visualizacao 2.jpg", "imagens/Top Regata Floral - visualizacao 3.jpg", "imagens/Top Regata Floral - visualizacao 4.jpg"],
    desc: "Top regata floral leve e versátil para combinações casuais.",
    composition: "100% viscose.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Comprimento"], "rows": [["PP", "78–82 cm", "58–62 cm", "48 cm"], ["P", "82–86 cm", "62–66 cm", "49 cm"], ["M", "86–90 cm", "66–70 cm", "50 cm"], ["G", "90–96 cm", "70–76 cm", "51 cm"]]},
    tags: "top regata floral rosa casual verão",
    promo: true,
    bestseller: true
  },

  {
    id: 22,
    name: "Vestido de Tricô Ombro a Ombro",
    category: "Vestidos",
    price: 99.90,
    color: "Bege",
    sizes: ["P", "M", "G"],
    occasion: "Romântico",
    image: "imagens/Vestido de Tricô Ombro a Ombro.jpg",
    images: ["imagens/Vestido de Tricô Ombro a Ombro.jpg", "imagens/Vestido de Tricô Ombro a Ombro - visualizacao 2.jpg", "imagens/Vestido de Tricô Ombro a Ombro - visualizacao 3.jpg", "imagens/Vestido de Tricô Ombro a Ombro - visualizacao 4.jpg"],
    desc: "Vestido de tricô ombro a ombro com visual delicado e aconchegante.",
    composition: "70% viscose e 30% poliamida.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "82–86 cm", "64–68 cm", "88–92 cm", "84 cm"], ["M", "86–90 cm", "68–72 cm", "92–96 cm", "86 cm"], ["G", "90–96 cm", "72–78 cm", "96–102 cm", "88 cm"]]},
    tags: "vestido trico ombro ombro bege romantico",
    promo: true,
    bestseller: false
  },

  {
    id: 23,
    name: "Vestido Vinho Frente Única",
    category: "Vestidos",
    price: 89.90,
    color: "Vinho",
    sizes: ["P", "M", "G"],
    occasion: "Festa",
    image: "imagens/Vestido Vinho Frente Única.jpg",
    images: ["imagens/Vestido Vinho Frente Única.jpg", "imagens/Vestido Vinho Frente Única - visualizacao 2.jpg", "imagens/Vestido Vinho Frente Única - visualizacao 3.jpg", "imagens/Vestido Vinho Frente Única - visualizacao 4.jpg"],
    desc: "Vestido vinho frente única com modelagem elegante para ocasiões especiais.",
    composition: "95% poliéster e 5% elastano.",
    measurements: {"headers": ["Tamanho", "Busto", "Cintura", "Quadril", "Comprimento"], "rows": [["P", "82–86 cm", "62–66 cm", "88–92 cm", "82 cm"], ["M", "86–90 cm", "66–70 cm", "92–96 cm", "84 cm"], ["G", "90–96 cm", "70–76 cm", "96–102 cm", "86 cm"]]},
    tags: "vestido vinho frente unica festa elegante",
    promo: true,
    bestseller: true
  },

  {
    id: 25,
    name: "Shorts Jeans Claro",
    category: "Shorts",
    price: 84.90,
    color: "Azul",
    sizes: ["PP", "P", "M", "G", "GG"],
    occasion: "Casual",
    image: "imagens/Short jeans.jpn.jpg",
    images: ["imagens/Short jeans.jpn.jpg", "imagens/Short jeans.jpn - visualizacao 2.jpg", "imagens/Short jeans.jpn - visualizacao 3.jpg", "imagens/Short jeans.jpn - visualizacao 4.jpg"],
    desc: "Shorts jeans claro com modelagem confortável, ideal para produções casuais no dia a dia.",
    composition: "98% algodão e 2% elastano.",
    measurements: {"headers": ["Tamanho", "Cintura", "Quadril", "Comprimento"], "rows": [["PP", "60–64 cm", "86–90 cm", "34 cm"], ["P", "64–68 cm", "90–94 cm", "35 cm"], ["M", "68–72 cm", "94–98 cm", "36 cm"], ["G", "72–78 cm", "98–104 cm", "37 cm"], ["GG", "78–84 cm", "104–110 cm", "38 cm"]]},
    tags: "shorts jeans claro casual verão",
    promo: false,
    bestseller: false
  },

  {
    id: 24,
    name: "Óculos Y2K com Estrelas",
    category: "Acessórios",
    price: 44.90,
    color: "Roxo",
    sizes: ["Único"],
    occasion: "Casual",
    image: "imagens/Óculos Y2K com Estrelas.jpg",
    images: ["imagens/Óculos Y2K com Estrelas.jpg", "imagens/Óculos Y2K com Estrelas - visualizacao 2.jpg", "imagens/Óculos Y2K com Estrelas - visualizacao 3.jpg", "imagens/Óculos Y2K com Estrelas - visualizacao 4.jpg"],
    desc: "Óculos inspirado na estética Y2K com detalhes de estrelas para completar o look.",
    composition: "Acetato e lentes sintéticas.",
    measurements: {"headers": ["Tamanho", "Largura da armação", "Altura da lente"], "rows": [["Único", "14 cm", "5 cm"]]},
    tags: "oculos y2k estrelas roxo acessorio",
    promo: true,
    bestseller: false
  }
];